-- MySQL Script generated by MySQL Workbench
-- Mon May 10 15:13:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Partx
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Partx` ;

-- -----------------------------------------------------
-- Schema Partx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Partx` DEFAULT CHARACTER SET utf8 ;
USE `Partx` ;

-- -----------------------------------------------------
-- Table `Partx`.`userTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Partx`.`userTypes` ;

CREATE TABLE IF NOT EXISTS `Partx`.`userTypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Partx`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Partx`.`users` ;

CREATE TABLE IF NOT EXISTS `Partx`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(90) NOT NULL,
  `phone_number` VARCHAR(10) NOT NULL,
  `profile_pic` VARCHAR(75) NOT NULL,
  `userTypes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  INDEX `fk_users_userTypes1_idx` (`userTypes_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_userTypes1`
    FOREIGN KEY (`userTypes_id`)
    REFERENCES `Partx`.`userTypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Partx`.`Places`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Partx`.`Places` ;

CREATE TABLE IF NOT EXISTS `Partx`.`Places` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(50) NULL,
  `postcode` VARCHAR(20) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `additional_infos` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Partx`.`eventsTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Partx`.`eventsTypes` ;

CREATE TABLE IF NOT EXISTS `Partx`.`eventsTypes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Partx`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Partx`.`events` ;

CREATE TABLE IF NOT EXISTS `Partx`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `pic` VARCHAR(75) NOT NULL,
  `date` DATE NOT NULL,
  `entry_price` FLOAT NOT NULL DEFAULT 0,
  `thingsTo_bring` MEDIUMTEXT NULL,
  `Description` LONGTEXT NOT NULL,
  `Places_id` INT NOT NULL,
  `eventTypes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `UniqueEvent` (`name` ASC, `date` ASC, `entry_price` ASC) VISIBLE,
  INDEX `fk_events_Places_idx` (`Places_id` ASC) VISIBLE,
  INDEX `fk_events_eventsTypes1_idx` (`eventTypes_id` ASC) VISIBLE,
  CONSTRAINT `fk_events_Places`
    FOREIGN KEY (`Places_id`)
    REFERENCES `Partx`.`Places` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_eventsTypes1`
    FOREIGN KEY (`eventTypes_id`)
    REFERENCES `Partx`.`eventsTypes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Partx`.`users_organize_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Partx`.`users_organize_events` ;

CREATE TABLE IF NOT EXISTS `Partx`.`users_organize_events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `events_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  INDEX `fk_events_has_users_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_events_has_users_events1_idx` (`events_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_events_has_users_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `Partx`.`events` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_events_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `Partx`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Partx`.`users_participate_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Partx`.`users_participate_events` ;

CREATE TABLE IF NOT EXISTS `Partx`.`users_participate_events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `events_id` INT NOT NULL,
  INDEX `fk_users_has_events_events1_idx` (`events_id` ASC) VISIBLE,
  INDEX `fk_users_has_events_users1_idx` (`users_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `UniqueParticipation` (`users_id` ASC, `events_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_events_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `Partx`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_has_events_events1`
    FOREIGN KEY (`events_id`)
    REFERENCES `Partx`.`events` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ---------------------------------------------------------
-- Default value
-- ---------------------------------------------------------
INSERT INTO usertypes (NAME)
VALUES ('Administrateur');
INSERT INTO usertypes (NAME) 
VALUES ('Utilisateur');

INSERT INTO eventstypes (NAME)
VALUES ('Festival');
INSERT INTO eventstypes (NAME)
VALUES ('Soirée');
INSERT INTO eventstypes (NAME)
VALUES ('Rave');
